### ISSUE TITLE
Figure out the time unit in kFcitx5NotificationTimeout

### ISSUE THREAD

**Issue by lukhnos** [openvanilla/fcitx5-mcbopomofo#117]
In https://github.com/openvanilla/fcitx5-mcbopomofo/pull/116 we introduced a constant (of value 1000) that passed to fcitx5's `Notifications::showTip`. From the source [^1] the parameter doesn't seem to be used other than be logged, and it's not clear what time unit is that, though millisecond seems to be the only reasonable guess given the magnitude. Filing this as a TODO.

[^1]: https://github.com/fcitx/fcitx5/blob/master/src/modules/notifications/notifications.cpp#L197

**Comment by xatier** [comment]
In `showTip`, parameter `timeout` is passed to `sendNotification`.

```cpp
    lastTipId_ = sendNotification(
        appName, lastTipId_, appIcon, summary, body, actions, timeout,
        [this, tipId](const std::string &action) {
      ...
    }
```

https://github.com/fcitx/fcitx5/blob/master/src/modules/notifications/notifications.cpp#L206

Inside `sendNotification`, `timeout` is passed to the `message` object, with `Message &Message::operator<<`.

```cpp
    auto message =
        bus_->createMethodCall(NOTIFICATIONS_SERVICE_NAME, NOTIFICATIONS_PATH,
                               NOTIFICATIONS_INTERFACE_NAME, "Notify");
    ...

    message << appName << replaceId << IconTheme::iconName(appIcon) << summary
            << body;
    message << actions;
    message << dbus::Container(dbus::Container::Type::Array,
                               dbus::Signature("{sv}"));
    message << dbus::ContainerEnd();
    message << timeout;
```

https://github.com/fcitx/fcitx5/blob/master/src/modules/notifications/notifications.cpp#L158

The `operator<<` is used to append the operand to dbus. Basically, this cpp file defines all kinds of `operator<<` to pack different types. In particular, `timeout` is an `int32_t`, hence it goes to the macro:

```cpp
#define _MARSHALL_FUNC(TYPE, TYPE2)                                            \
    Message &Message::operator<<(TYPE v) {                                     \
        if (!(*this)) {                                                        \
            return *this;                                                      \
        }                                                                      \
        FCITX_D();                                                             \
        d->lastError_ = !dbus_message_iter_append_basic(                       \
            d->iterator(), DBUS_TYPE_##TYPE2, &v);                             \
        return *this;                                                          \
    }     

_MARSHALL_FUNC(int32_t, INT32)
```

https://github.com/fcitx/fcitx5/blob/master/src/lib/fcitx-utils/dbus/libdbus/message.cpp#L284

----

Now, let's move our focus back to `notifications.cpp`

```
#define NOTIFICATIONS_SERVICE_NAME "org.freedesktop.Notifications"
#define NOTIFICATIONS_INTERFACE_NAME "org.freedesktop.Notifications"
#define NOTIFICATIONS_PATH "/org/freedesktop/Notifications"

    auto message =
        bus_->createMethodCall(NOTIFICATIONS_SERVICE_NAME, NOTIFICATIONS_PATH,
                               NOTIFICATIONS_INTERFACE_NAME, "Notify");
```

https://github.com/fcitx/fcitx5/blob/master/src/modules/notifications/notifications.cpp#L17

This leads us to the `Table 6. Notify Parameters` in `Desktop Notifications Specification`.

```
Table 6. Notify Parameters

expire_timeout	INT32	
The timeout time in milliseconds since the display of the notification at which the notification should automatically close.

If -1, the notification's expiration time is depend
```

https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html

I hope this helps!

**Comment by xatier** [comment]
Btw, there are a few simpler examples on Arch wiki that explain how this works. The C example is quite close to what `notifications.cpp` and `message.cpp` are doing. The only difference is that fcitx encapsulated dbus message objects in `messages.cpp`.

https://wiki.archlinux.org/title/Desktop_notifications#C

**Comment by lukhnos** [comment]
Ah! I failed to notice that the `<<` operator was actually used to build a message, not logging. Just added 62d07769f2c16ce93f06e87b1756d90e3055255c to clarify the time unit used, and I learned a lot from this. Thanks for such a detailed walkthrough!

**Comment by xatier** [comment]
No worries , this is basically a builder pattern in C++'s confusing operator overloading.
