### ISSUE TITLE
Phrase suggestions issue with user-defined pronunciations 

### ISSUE THREAD

**Issue by xatier** [openvanilla/fcitx5-mcbopomofo#118]
Hi,

It seems that if the user has some customized pronunciations for certain characters in their `data.txt`, it will confuse the phrase suggestion language model with undesired results.

For instance, if I have the following in my `data.txt`.

```
丼 ㄉㄨㄥˋ
❤️  ㄒㄧㄣ
```

The default phrase will include the characters with customized pronunciations, it requires an extra transform (hit the space key) to obtain the desired results.

Default: 丼作
Expected: 動作

![image](https://github.com/openvanilla/fcitx5-mcbopomofo/assets/1911178/1763940a-b325-463f-a49a-fee39afb952e)

Default: ❤️苦
Expected: 辛苦
![image](https://github.com/openvanilla/fcitx5-mcbopomofo/assets/1911178/87e7214e-603a-4469-ab5e-63b7787d6fa5)

Perhaps we can adjust the priority of the default suggestion if there exists some other phrases in the dictionary that match the pronunciation of the entire phrase? E.g., when typing `ㄉㄨㄥˋㄗㄨㄛˋ`, as `動作` matches the pronunciations of the entire phrase, we provide `動作` as the default.

**Comment by lukhnos** [comment]
@xatier Thanks for bringing this up. If you have a chance, could you try if the branch https://github.com/openvanilla/fcitx5-mcbopomofo/tree/dev/fairer-user-phrase-scores fixes the issue?

**Comment by xatier** [comment]
@lukhnos thanks for the prompt fix! This patch works as expected!

**Comment by xatier** [comment]
Typing sequence:

`ㄒㄧㄣㄎㄨ`
![image](https://github.com/openvanilla/fcitx5-mcbopomofo/assets/1911178/f5f983c4-ab60-4e10-9063-a6fcc61ea521)
`ㄒㄧㄣㄎㄨˇ`
![image](https://github.com/openvanilla/fcitx5-mcbopomofo/assets/1911178/b8a44349-70bc-4342-b583-b17144f6c481)
`ㄒㄧㄣㄎㄨˇ[space]`
![image](https://github.com/openvanilla/fcitx5-mcbopomofo/assets/1911178/fd9380a4-dd5a-422b-bec7-cbd9c9359d00)
