### ISSUE TITLE
更新 Fedora 安裝說明 （支援 Fedora 39）

### ISSUE THREAD

**Issue by jimchen5209** [openvanilla/fcitx5-mcbopomofo#124]
上次在 #77 提供的安裝說明需要更新

在第一部安裝套件的部分，更新為
```
sudo dnf install fcitx5 fcitx5-configtool \
                 fcitx5-devel cmake extra-cmake-modules gettext fmt-devel libicu-devel json-c-devel
```

變更部分：
- 新增必要相依套件：`libicu-devel`、`json-c-devel`
- 移除 `fcitx5-autostart`

附註說明：
- `fcitx5-autostart` 為 X11 用的開機啟動， Wayland 現在不需安裝此套件，設定方式請參考 [fcitx5 wiki](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma)

**Comment by lukhnos** [comment]
已修訂 [wiki 頁面]，感謝提供更新說明！
