### ISSUE TITLE
Proposal: reformat the code in src/Engine to using Google C++ style

### ISSUE THREAD

**Issue by lukhnos** [openvanilla/fcitx5-mcbopomofo#125]
For the longest time the C++ code of McBopomofo was written (very loosely) in the WebKit style. Now that a lot of C++ work is actively done in fcitx5-mcbopomofo (then it gets synced over to McBopomofo, the macOS project), I think we can unify the style by making a one-time PR both here and to the macOS project. Compared to other files in fcitx5-mcbopomofo, those in `src/Engine/` excluding gramambular2 and Mandarin are the only ones that still follow the WebKit style.

One additional benefit is that we can run `cpplint` over the reformatted code.

**Comment by xatier** [comment]
Sounds good to me, let's keep the coding style consistent across the repo.
