### ISSUE TITLE
Add developer tag in metainfo

### ISSUE THREAD

**Issue by wengxt** [openvanilla/fcitx5-mcbopomofo#127]
https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name

This is now required on flathub, otherwise no new build can be done on flathub.

Example change that I did for other fcitx5 package:

https://github.com/fcitx/fcitx5-chewing/commit/fcbd44d6baae2200117413639f64aefbd9d57c80

**Comment by lukhnos** [comment]
Resolved via d963b4e0203598df77e863bf6d41e89767df7800. Thanks for letting us know!
