### ISSUE TITLE
[詞庫問題] 輸入ㄏㄨㄚ會優先使用化而不是花

### ISSUE THREAD

**Issue by Brli** [openvanilla/fcitx5-mcbopomofo#144]
不覺得這個應該是使用頻率的問題
但好像就是怎樣都不會校正回更常用的花
而不是正常來講是四聲的化

**Comment by tianjianjiang** [comment]
> 不覺得這個應該是使用頻率的問題 但好像就是怎樣都不會校正回更常用的花 而不是正常來講是四聲的化

@Brli 感謝提問！
這方面要修正稍微有點複雜。頻率目前只針對字詞，沒有特別區分什麼注音更常用什麼字詞。
我會跟其他主要作者們討論一下能否找到最快修正這種現象的方法。

**Comment by zonble** [comment]
這個得要從詞庫下手，感覺是個大工程。

我自己比較困擾的是另外一個 case，當「法」念成四聲的時候，第一個出現的是「琺」，這也不太對。

**Comment by tianjianjiang** [comment]
> 這個得要從詞庫下手，感覺是個大工程。
> 
> 我自己比較困擾的是另外一個 case，當「法」念成四聲的時候，第一個出現的是「琺」，這也不太對。

@zonble 我在想，如果不動詞庫，或許要在程式裡對單字詞的候選列表開個特例，讓它改用 cin 的字序。
+CC @lukhnos @mjhsieh

**Comment by lukhnos** [comment]
Fixed in HEAD (806528c153da5414affe59646c685c47a3cbef8f) via https://github.com/openvanilla/McBopomofo/pull/515
