### ISSUE TITLE
候選字框位移

### ISSUE THREAD

**Issue by kizuna0487** [openvanilla/fcitx5-mcbopomofo#145]
您好，我在使用小麥注音Linux版本時遇到，在Firefox125版本底下，任一網頁如google.com中輸入中文並選字時，候選字的框並未如預期的在文字輸入欄中出現，而是在其他螢幕畫面中，我是三螢幕使用者

系統版本：Ubuntu 24.04 LTS

我不太清楚這是小麥注音的問題還是說fcitx5對於24.04版本相容性問題

**Comment by zonble** [comment]
小麥注音的邏輯當中其實不包括選字窗的位置，如果除了小麥注音以外，換到其他輸入法也有問題的話，那就比較可能是 fcitx 的問題。

不過，如果其他應用程式都沒問題，就只有 Firefox 會出問題的話，那也很有可能是 Firefox 的問題。通常是應用程式得對外告訴輸入法現在使用者的焦點在哪個位置。

**Comment by kizuna0487** [comment]
非常感謝您的回覆以及提供線索，我會再繼續尋找此問題發生的相關原因，這邊我就先close這個問題
