### ISSUE TITLE
[Feature] 建議在設定中新增自訂字典

### ISSUE THREAD

**Issue by olivertzeng** [openvanilla/fcitx5-mcbopomofo#150]
雖然已經有Shift+左右鍵enter 但是好像還不夠。因為如果想要從之前不小心增加的詞刪除的話就沒辦法這樣作。

**Comment by xatier** [comment]
I believe you can always invoke the text editor to update the user dictionary.

**Comment by olivertzeng** [comment]
> I believe you can always invoke the text editor to update the user dictionary.
> 
> 
> 
> ref: https://github.com/openvanilla/fcitx5-mcbopomofo/pull/36

Ok I'll go take a look
I'll remain this issue open until I figure out the solution ig.
