### ISSUE TITLE
Doesn't work with the latest fcitx5 Flatpak

### ISSUE THREAD

**Issue by fsworld009** [openvanilla/fcitx5-mcbopomofo#161]
## Environment
KDE Plasma (Wayland) 6.2.2
McBopomofo Version: 2.8.1

## Current fcitx5 versions (at the time of writing this issue)

```
$ flatpak remote-info --log flathub org.fcitx.Fcitx5

    Commit: 92f67d4acfd6062876e9cbfb39450cc76b8ccec2ab34c9a565c16898cf1beda0
    Parent: 7174c2f1842e421351d003cba5c78c605015e263329da58e48e93907f4166d65
   Subject: Update org.fcitx.Fcitx5 to tag-5.1.11 (#39) (6ddd6703)
      Date: 2024-11-08 13:35:33 +0000
   History: 

    Commit: 7174c2f1842e421351d003cba5c78c605015e263329da58e48e93907f4166d65
   Subject: libuv: Update libuv to 1.49.2 (#38) (b21d4641)
      Date: 2024-10-20 07:14:52 +0000
```

## Issue

With the current latest fcitx5 (92f67d), Both Plain Bopomofo and McBopomofo becomes unusable:

1. When switching to the IME, it would show `Plain Bopomofo (Not available)` or `McBopomofo (Not available)`.
2. Can only type in Englisth

Manually revert fcitx5 to the previous commit

```
flatpak update --commit=7174c2f1842e421351d003cba5c78c605015e263329da58e48e93907f4166d65 org.fcitx.Fcitx5
```

and restart fcitx5 would make them work again.

The other IME I'm using (Mozc) doesn't have this issue, so I suppose it's an issue specific to this IME, thanks.

**Comment by lukhnos** [comment]
I can repro this, and this is what I saw when I ran `flatpak run org.fcitx.Fcitx5` with the latest Flatpak fcitx5 (at the comment mentioned above):

```
addonloader.cpp:38] Failed to load library for addon mcbopomofo on /app/addons/McBopomofo/lib/fcitx5/m
cbopomofo.so. Error: libicuuc.so.73: cannot open shared object file: No such file or directory

addonmanager.cpp:201] Could not load addon mcbopomofo
```

I still don't feel that I understand how Flatpak really works. Does the missing (?) `libicuuc.so.73` ring a bell to you?

**Comment by lukhnos** [comment]
This should be fixed the merge of https://github.com/flathub/org.fcitx.Fcitx5.Addon.McBopomofo/pull/9. It'll take a few hours before the updated fcitx5-mcbopomofo flatpak package gets published to flathub. I'll keep this issue open until then.

**Comment by lukhnos** [comment]
Fixed with the latest stable package of `org.fcitx.Fcitx5.Addon.McBopomofo` at commit `3bb8138`. Here's what I saw when I ran `flatpak remote-info --log flathub org.fcitx.Fcitx5.Addon.McBopomofo`:

```
        ID: org.fcitx.Fcitx5.Addon.McBopomofo
       Ref: runtime/org.fcitx.Fcitx5.Addon.McBopomofo/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 8.2 MB
 Installed: 27.9 MB

    Commit: 3bb8138353caa582c5a9627a92fdc4035ca29ecd7d4e3a9c729887c563f8cfca
    Parent: 31e059f40938875d6e5ed21d55bbe841b7cfb2429d41eabd5ba7c5ae8dd421b0
   Subject: Update appstream-compose config (fd8a8b8f)
      Date: 2024-11-10 08:07:43 +0000
```

`flatpak list` will still list the installed version as 2.8.1. Thanks for letting us know the issue!

**Comment by fsworld009** [comment]
Confirmed it's working now. Appreciate your quick response :+1:
