### ISSUE TITLE
能否增加選項讓 Caps lock 開啟時依然能輸入中文和小寫英文？

### ISSUE THREAD

**Issue by magiclen** [openvanilla/fcitx5-mcbopomofo#163]
以微軟新注音來說，當 Caps Lock 開啟時，直接按下英文字母按鍵依然可以繼續拚打中文注音。如果是按住 SHIFT 後按下英文字母按鍵，則會打出英文小寫字母。

但小麥輸入法的行為則似乎只能是：當 Caps Lock 開啟時，直接按下英文字母按鍵會打出大寫英文字母。如果是按住 SHIFT 後按下英文字母按鍵，則可以繼續拚打中文注音（但由於注音聲調也打不出來，所以沒什麼用處）。

這邊只是用英文字母的按鍵來舉例，其它的按鍵的邏輯略有不同。換個方式描述的話，即 Caps Lock 在微軟新注音中只會把大小寫英文字母對調，但 Caps Lock 在小麥輸入法中，Caps Lock 開啟時按下英文字母按鍵卻像是預設就把 SHIFT 按住了，要按住 SHIFT 才能取消 SHIFT 按住的效果，但是按其它非英文字母的按鍵則沒有「預設就把 SHIFT 按住了」這樣的效果。

由於 Caps lock 的行為差異巨大，所以建議小麥輸入法能提供選項讓 Caps Lock 用起來能夠和微軟新注音一樣。

**Comment by zonble** [comment]
在 #165 增加了這項設定，會跟著下個版本一起發布。
