### ISSUE TITLE
能否增加 SHIFT 加上標點符號按鍵會正常打出原本英文鍵盤的標點符號的選項？

### ISSUE THREAD

**Issue by magiclen** [openvanilla/fcitx5-mcbopomofo#164]
如下圖，在 WIKI 中有特別提到小麥輸入法對於標點符號輸入的特別處理：

![image](https://github.com/user-attachments/assets/d40558f7-18bc-4863-814e-c1dc19e5d3a1)

但對於如我這樣習慣使用微軟新注音輸入法的使用者來說，使用上就會卡卡的。例如我想輸入半形小於 `<`，在微軟新注音中我只需要按下 <kbd>Shift + ,</kbd>，但是用小麥輸入法我就要先按 <kbd>Shift + ,</kbd> 輸入 `,` 之後，再按下 <kbd>↓</kbd> 來選擇 <kbd><</kbd>。

小麥輸入法的標點符號都會進緩衝區，要按下 <kbd>Enter</kbd> 才能輸入，如此雖能允許使用者可以在緩衝區中去更改已經輸入過的標點符號，但也讓標點符號的輸入要多一個按 <kbd>Enter</kbd> 鍵的步驟才能輸入完成。或許可以參考微軟新注音輸入法的做法，在使用者輸入標點符號前就有機會精準地輸入標點符號，且在輸入句號或是逗號時就自動確認緩衝區中的字。另外，當緩衝區沒有任何字時，輸入標點符號則可直接輸入該標點符號而不再進緩衝區，這樣子就不用再多一個無謂的按 <kbd>Enter</kbd> 鍵確認輸入的步驟。

**Comment by zonble** [comment]
您好：

這項需求可以透過小麥的一項進階功能 [手動刪詞](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A#%E6%89%8B%E5%8B%95%E5%88%AA%E8%A9%9E) 達成

1. 打開刪詞定義檔。這個檔案可以從輸入法選單中的 "Edit excluded phrase" 中打開，或是直接去編輯 ~/.local/share/fcitx5/mcbopomofo/exclude-phrases.txt

![input menu](https://github.com/user-attachments/assets/e8b00ba7-6968-4373-bfcb-096cedeb049d)


2. 貼上以下內容

```
， _punctuation_<
， _punctuation_Standard_<
〈 _punctuation_Standard_<
《 _punctuation_Standard_<
︿ _punctuation_Standard_<
︽ _punctuation_Standard_<
。 _punctuation_>
。 _punctuation_Standard_>
． _punctuation_>
． _punctuation_Standard_>
〉 _punctuation_Standard_>
》 _punctuation_Standard_>
﹀ _punctuation_Standard_>
︾ _punctuation_Standard_>
```
