### ISSUE TITLE
處理 Chrome 系列瀏覽器吃字的問題

### ISSUE THREAD

**Issue by zonble** [openvanilla/fcitx5-mcbopomofo#24]
在使用 Chrome 引擎的瀏覽器當中打字時，如果對 fcitx5 的 input context 呼叫了 commitString() API 的話，那麼輸入法引擎就會收到一個 focus out 事件，並且呼叫到 reset() 方法。

如果我們真的在 reset() 方法中，清除掉了目前用戶輸入的注音 reading 以及 composing buffer，由於小麥的邏輯是注音 reading 超過上限之後，就會用 commitString 輸入超過上限的部分，如果這時候因為 focus out 而被清除，就會有種用戶打字到一半，有些字直接不見的狀況，而造成用戶難以輸入整段文字。另一方面，用戶在使用 Chrome 系列瀏覽器（包括 Chrome、Chromium、MS Edge、Sidekick 等）以及 Electron 瀏覽器打字的場合，真的非常多。

目前先暫時寫死幾組需要忽略 focus out 的瀏覽器，但我們應該把這應該排除的 app 做得更靈活些。

**Comment by lukhnos** [comment]
實測了一下，發現並不是所有網頁的 text field 都有這個問題。Twitter 輸入框是最容易重現的。

另一個問題是在我的機器上，`context->program()` 回應的是空字串，我只能猜測原因（例如 fcitx5 API 版本差異）但沒有深究。

也許根本解決之道是修改輸入法選字引擎，把 eviction 行為取消。不過這樣一來，衍生的問題是，要允許多長的組字區呢...

總之先根據 FocusOut 事件的本質跟發生順序，用實驗法決定了一個門檻，發了 #26 ，看看是否可以作為當前問題的通用解。
