### ISSUE TITLE
Suggestion: no need to have your own dvorak implementation

### ISSUE THREAD

**Issue by wengxt** [openvanilla/fcitx5-mcbopomofo#28]
Fcitx5 basically allow you to manage keyboard layout at the same time.

It's even possible even if you want to keep display server layout to non-dvorak and only ues dvorak for certain engines.

(KDE's configtool, qt version has same functionality but different UI).
![图片](https://user-images.githubusercontent.com/259684/160671007-7d344d8d-076e-4208-a5c2-5c9266eb3223.png)

**Comment by lukhnos** [comment]
Thanks! I implemented our own mapper because I couldn't figure out how to make this work and mistakenly thought it was not something fcitx5 had a solution for. Now I found the settings (I use the qt version) and it works perfectly, and I made #31 to remove our own implementation.
