### ISSUE TITLE
UI hangs on 'Edit User Phrases'

### ISSUE THREAD

**Issue by xatier** [openvanilla/fcitx5-mcbopomofo#30]
In `McBopomofoEngine::McBopomofoEngine`, we leverage `xdg-open` to invoke the user-preferred text editor. However, the desktop environment hangs if `system()` invokes a synchronous command. For instance, the default text editor on my box is set to `vim`.

The lambda invoked by `fcitx5::SimpleAction` will never return since `vim` is not opened in a proper environment (e.g., terminal emulator).

https://github.com/openvanilla/fcitx5-mcbopomofo/blob/master/src/McBopomofo.cpp#L176-L190 

Reproduce:

1) Set the default text editor to `vim`.

```bash
xdg-mime default vim.desktop text/plain
```

2) click "Edit User Phrases" on the menu.

**Comment by lukhnos** [comment]
Would replacing the `system()` call to [`fcitx::startProcess()`](https://github.com/fcitx/fcitx5/blob/master/src/lib/fcitx-utils/misc.h#L106) fix the problem?

**Comment by xatier** [comment]
I'm not exactly sure what should be the more proper way though.

Surely `startProcess` should invoke the subprocess properly [1], but in this particular case, it's pretty much pointless to open the `vim` process in the background. To handle this case properly, we can launch `vim` with some terminal emulator (see [2] for reference). Alternatively, we can make `xdg-open` to be a user configurable path to the preferred (GUI) editors.

[1] https://github.com/fcitx/fcitx5/blob/749e73633e1786f501ac39f0b8f2cee7dafdf60e/src/lib/fcitx/instance.cpp#L1844
[2] https://github.com/ChildishGhost/einstein/blob/dev/plugins/desktop/LinuxDesktopApplicationSearchEngine.ts#L249-L256

**Comment by lukhnos** [comment]
> In this particular case though, it's pretty much pointless to open the vim process in the background.

I see the point now. Strangely, I couldn't repro the issue using your steps on my Ubuntu 20.04 LTS box. `xdg-open` there seemed to know to launch the Terminal app and then launch vim there. Could it be that Ubuntu configures `xdg-open` differently that it knows to avoid the issue of launching an unusable process in the foreground or background?

Still, I'm keeping this issue open now. As it stands it's a pretty bad user experience.

**Comment by xatier** [comment]
I'm not sure how Ubuntu environment is configured, but in general: 

The way it works is that `xdg-open` would try to find the associated app with the given mine type, then invoke the command in `Exec=` field from the `.desktop` file.

```bash
$ xdg-mime query default text/plain
vim.desktop

$ grep ^Exec= /usr/share/applications/vim.desktop
Exec=vim %F
```

See [1] for details. Common minetype associations can be found here [2].

[1] https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html
[2] https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list

**Comment by xatier** [comment]
With some research, I came across this bug [1] and this SO anser [2].

I'm not using desktop environments (I use AwesomeWM), hence `xdg-open` will not spawn the terminal emunator for me. 

[1] https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/84
[2] https://unix.stackexchange.com/a/590093

**Comment by xatier** [comment]
Pretty interesting behavior in Ubuntu/gnome indeed.

Basically `xdg-open ~/.local/share/fcitx5/mcbopomofo/data.txt` will be translated to `gio open ~/.local/share/fcitx5/mcbopomofo/data.txt`, which would look for the proper terminal emulator based the user's gnome preferences [1].

screenshot from a ubuntu VM.

![2022-03-31_03-37](https://user-images.githubusercontent.com/1911178/161014019-0d518d20-cf75-4d99-804e-c3dcd4090538.png)

On my environment, it goes to `open_generic` [2].

[1] https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/master/scripts/xdg-open.in#L533
[2] https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/master/scripts/xdg-open.in#L573

**Comment by lukhnos** [comment]
Thanks for the investigation. How would you fix this issue? For example, should we at least try _not_ to show the menu items by reading the `XDG_CURRENT_DESKTOP` environment variable and be safe if `xdg-open` will take the generic route?

**Comment by xatier** [comment]
Here are a few things IMO:

1. if `XDG_CURRENT_DESKTOP` is present, it should be safe to use `xdg-open` under Gnome. I have no idea whether other handlers such as `open_kde` would invoke the terminal emulator. In many cases, `xdg-open` still calls `open_generic` if the DE specific handler (e.g. `gio`, `gvfs-open`) is not found.
2. We don't need to _hide_ the menu, but it would be great to introduce another config to let the user set their preferred way to launch the editor. Something like `COMMAND %s`, `%s` being `data.txt` or `exclude-phrases.txt`.
3. We can show some warning message in the config menu and mention this issue.
