### ISSUE TITLE
不會自動建立 .local/share/fcitx5/mcbopomofo

### ISSUE THREAD

**Issue by zonble** [openvanilla/fcitx5-mcbopomofo#52]
在使用 debian 的時候發現的。fcitx5 在載入小麥注音的時候，如果沒有 .local/share/fcitx5/mcbopomofo 這個目錄，就會造成小麥注音載入失敗。建立這個目錄之後重跑 fcitx5 就會成功，但照理說應該要自動建立這個目錄才對。

**Comment by lukhnos** [comment]
這跟 fcitx5 的版本有關嗎？在 Ubuntu 22.04 LTS 上裝的 fcitx5 無此問題...

我記得之前在 Raspberry Pi 上嘗試安裝時，[也遇過同樣問題](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/Raspberry-Pi-OS#%E5%B7%B2%E7%9F%A5%E5%95%8F%E9%A1%8C)。如果沒記錯的話，問題不只在於 ` .local/share/fcitx5/mcbopomofo` 還不存在，而是如果上一層的 ` .local/share/fcitx5` 不存在， 模組在嘗試從 fcitx5 取得 local data directory 時就會出問題。

**Comment by lukhnos** [comment]
也就是說，如果 `.local/share/fcitx5` 已經存在，那麼 fcitx5 應該是會建立 `.local/share/fcitx5/mcbopomofo` 的。

**Comment by wengxt** [comment]
一般來說 fcitx5 自己並沒有自動一啓動就建立 ~/.local/share/fcitx5 的需求，如果有，那也是別的引擎/addon等進行的操作，如果某個引擎需要，他應該自己建立包括上層路徑的所有路徑

舉個例子，可以在初始化階段寫一段這樣的代碼來建立路徑
https://github.com/fcitx/fcitx5-rime/blob/cc3e0498dc8be20806cdea3df13698b54065b145/src/rimeengine.cpp#L162

**Comment by zonble** [comment]
@wengxt 謝謝，看來我們得自己調整一下。 :)
