### ISSUE TITLE
Feature request: Appstream / Flatpak 支持以及添加到 Flathub

### ISSUE THREAD

**Issue by wengxt** [openvanilla/fcitx5-mcbopomofo#54]
Fcitx 5 是可以支持運作在 flatpak 當中的 (https://flatpak.org/)，現在已有不少 Fcitx 5 的其他引擎在 flathub 上

整體代碼來說一般並不需要做任何修改，具體編譯方式和安裝路徑可以參考 https://github.com/fcitx/flatpak-fcitx5/ 的其他任一引擎

因爲 flathub 一般是採取 maintainer 自己提交的方式，因此最好由你們自己申請。至於申請流程可以參考：https://github.com/flathub/flathub/wiki/App-Submission

目前觀察 repo 的文件，主要問題是缺少一個 metainfo 的文件（spec： https://www.freedesktop.org/wiki/Distributions/AppStream/）

隨便舉一例可以參考添加上： https://github.com/fcitx/fcitx5-rime/blob/master/org.fcitx.Fcitx5.Addon.Rime.metainfo.xml.in

即使不考慮支持 flatpak 的使用情況，添加這樣一個文件在被發行版收錄時也會在現行軟件商店中展示（現在GNOME和KDE的軟件商店只展示有appdata的包，而不展示任意發行版的deb package）

（如圖，搜索 fcitx 的結果，這樣的包的展示的名稱說明都來自對應的 metainfo.xml）
![图片](https://user-images.githubusercontent.com/259684/177059294-3d85a176-4df2-495c-a887-0f6ddb143357.png)

相對來講，我認爲 flathub 是一個很方便的能快速讓軟體能被最終用戶用上的方法，例如相對古早的 Ubuntu， 未有提供 fcitx5 的 RHEL 也可以利用 flatpak 運行最新的 fcitx5

**Comment by zonble** [comment]
@wengxt 謝謝，我們來研究一下，之前沒有做過 flatpak。 :)

**Comment by zonble** [comment]
Hi @wengxt 

因为对 flatpak 实在很不熟悉，想向您请教一些技术问题。

我先开了一个分支，位在 https://github.com/zonble/fcitx5-mcbopomofo/tree/master/distro/flatpak

我们的项目目前依赖 fmt，我参考了一下 fcitx 的库，在 yaml 的设置中，应该是先编译 fmt，然后再编译我们的输入法。不过，我实际运行 flatpak-builder 的时候，遇到的状况是，fmt 的确下载并且编起来了，但是在编译输入法的时候，Cmake 还是找不到 fmt，也就是无法通过 `find_package(fmt REQUIRED)` 这行。

就您的经验，这可能是什么问题呢？

谢谢！

**Comment by xatier** [comment]
@wengxt, would you like to take a glance at https://github.com/openvanilla/fcitx5-mcbopomofo/pull/70 ?

**Comment by wengxt** [comment]
> Hi @wengxt
> 
> 因为对 flatpak 实在很不熟悉，想向您请教一些技术问题。
> 
> 我先开了一个分支，位在 https://github.com/zonble/fcitx5-mcbopomofo/tree/flatpak/distro/flatpak
> 
> 我们的项目目前依赖 fmt，我参考了一下 fcitx 的库，在 yaml 的设置中，应该是先编译 fmt，然后再编译我们的输入法。不过，我实际运行 flatpak-builder 的时候，遇到的状况是，fmt 的确下载并且编起来了，但是在编译输入法的时候，Cmake 还是找不到 fmt，也就是无法通过 `find_package(fmt REQUIRED)` 这行。
> 
> 就您的经验，这可能是什么问题呢？
> 
> 谢谢！

@zonble 你的名字和路径不一致，不知道 flatpak 这里弄了什么魔法约定，但如果你把包名改成 McBopomofo 就能过了

**Comment by Brli** [comment]
Hi there,
I've set up a working yaml for flatpak bundle generator
https://github.com/Brli/flatpak.fcitx5-mcbopomofo

perhaps it will help.

**Comment by Brli** [comment]
Just noticed that
https://github.com/tinywrkb/org.fcitx.Fcitx5
Thus repo has several interesting patches and commits regards upstream and mcbopomofo.

**Comment by lukhnos** [comment]
感謝 @Brli 數個月前的努力，小麥注音現在可以用 flatpak 安裝了。我們寫了[如何透過 flatpak 安裝的 wiki](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/Flatpak)。再次謝謝大家！

**Comment by xatier** [comment]
awesome! thanks so much for the effort!

**Comment by Brli** [comment]
有請 @wengxt 把圖示加進去 fcitx 的 flatpak 嗎？

**Comment by lukhnos** [comment]
> 有請 @wengxt 把圖示加進去 fcitx 的 flatpak 嗎？

不太明白。這個需要做哪些事情呢？

**Comment by wengxt** [comment]
图示是什么？ @Brli

**Comment by Brli** [comment]
就是這行以下 https://github.com/fcitx/flatpak-fcitx5/blob/master/org.fcitx.Fcitx5.yaml#L69
aka. https://github.com/fcitx/flatpak-fcitx5/blob/master/install_icons 這個腳本在做的事情
因為 flatpak 的隔離機制，若不是由 fcitx 本體去載入這些圖示的話，直接安裝小麥，功能上沒問題，但是在輸入法面板的圖示就會闕如。

**Comment by Brli** [comment]
已經針對 flatpak-fcitx5 發了個 PR，https://github.com/fcitx/flatpak-fcitx5/pull/9
請參閱
