### ISSUE TITLE
please include pot file

### ISSUE THREAD

**Issue by Brli** [openvanilla/fcitx5-mcbopomofo#71]
https://github.com/openvanilla/fcitx5-mcbopomofo/blob/e611aa7654e8356dd77e493b51b1c3ff7b90a76c/run-xgettext.sh#L27

developers cannot update new strings without correct pot file.

please include it into git repo.

also, the regenerate line commented above has duplicated po/ directory.

**Comment by Brli** [comment]
also, the regenerate line commented above has duplicated po/ directory.

**Comment by lukhnos** [comment]
> developers cannot update new strings without correct pot file.

Question (as I know very little about i18n on Linux): I thought the files are always generated from the source code / po files. Does including pot files make it possible for developers to work on l10n updates without having to run the gettext script?

**Comment by lukhnos** [comment]
This is fixed via #72.
