### ISSUE TITLE
Fedora 37 安裝說明

### ISSUE THREAD

**Issue by jimchen5209** [openvanilla/fcitx5-mcbopomofo#77]
最近在嘗試 fedora 然後想安裝小麥輸入法，目前有試出一個安裝的方案。
方法跟 Readme 上的差不多，只差在相依安裝的方式不同

1. 安裝 fcitx5, CMake, 以及以下開發用模組：

```
sudo dnf install fcitx5 fcitx5-configtool fcitx5-autostart fcitx5-devel cmake extra-cmake-modules gettext fmt-devel
```

2. 然後在本專案的 git 目錄下執行以下指令：

```
mkdir -p build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
make
sudo make install
```

**Comment by xatier** [comment]
Update the [wiki](https://github.com/openvanilla/fcitx5-mcbopomofo/wiki) maybe?

**Comment by lukhnos** [comment]
@jimchen5209 @xatier 新增了 wiki 頁面，也更新了 wiki 首頁。感謝提供這項安裝說明！

* https://github.com/openvanilla/fcitx5-mcbopomofo/wiki/如何在-Fedora-上安裝-fcitx5-mcbopomofo
* https://github.com/openvanilla/fcitx5-mcbopomofo/wiki

**Comment by xatier** [comment]
awesome, thanks!
